[tool.poetry]
name = "lrac"
version = "0.1.0"
description = ""
authors = ["Nicholas M. Synovic <nicholas.synovic@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
feedparser = "^6.0.11"
pandas = "^2.2.0"
pyarrow = "^15.0.0"
progress = "^1.6"
sqlalchemy = "^2.0.27"
requests = "^2.31.0"
click = "^8.1.7"
bs4 = "^0.0.2"
lxml = "^5.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
